apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "polardbxcluster-validate.polardbx.aliyun.com"
webhooks:
- admissionReviewVersions:
  - "v1"
  clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.polardbx.aliyun.com/v1/validate-polardbx-aliyun-com-v1-polardbxcluster
  name: "polardbxcluster-validate.polardbx.aliyun.com"
  sideEffects: None
  rules:
  - apiGroups:
    - polardbx.aliyun.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - polardbxclusters
    scope: "Namespaced"
- admissionReviewVersions:
  - "v1"
  clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.polardbx.aliyun.com/v1/validate-polardbx-aliyun-com-v1-polardbxclusterknobs
  name: "polardbxclusterknobs-validate.polardbx.aliyun.com"
  sideEffects: None
  rules:
  - apiGroups:
    - polardbx.aliyun.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - polardbxclusterknobs
    scope: "Namespaced"
- admissionReviewVersions:
    - "v1"
  clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.polardbx.aliyun.com/v1/validate-polardbx-aliyun-com-v1-polardbxparameter
  name: "polardbxparameter-validate.polardbx.aliyun.com"
  sideEffects: None
  rules:
    - apiGroups:
        - polardbx.aliyun.com
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - polardbxparameters
      scope: "Namespaced"
- admissionReviewVersions:
    - "v1"
  clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.polardbx.aliyun.com/v1/validate-polardbx-aliyun-com-v1-polardbxbackup
  name: "polardbxbackup-validate.polardbx.aliyun.com"
  sideEffects: None
  rules:
    - apiGroups:
        - polardbx.aliyun.com
      apiVersions:
        - v1
      operations:
        - CREATE
      resources:
        - polardbxbackups
      scope: "Namespaced"
- admissionReviewVersions:
    - "v1"
  clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.polardbx.aliyun.com/v1/validate-polardbx-aliyun-com-v1-polardbxbackupbinlog
  name: "polardbxbackupbinlog-validate.polardbx.aliyun.com"
  sideEffects: None
  rules:
    - apiGroups:
        - polardbx.aliyun.com
      apiVersions:
        - v1
      operations:
        - CREATE
      resources:
        - polardbxbackupbinlogs
      scope: "Namespaced"
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "polardbxcluster-mutate.polardbx.aliyun.com"
webhooks:
- admissionReviewVersions:
  - "v1"
  clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.polardbx.aliyun.com/v1/mutate-polardbx-aliyun-com-v1-polardbxcluster
  name: "polardbxcluster-mutate.polardbx.aliyun.com"
  sideEffects: None
  rules:
  - apiGroups:
    - polardbx.aliyun.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - polardbxclusters
    scope: "Namespaced"
- admissionReviewVersions:
  - "v1"
  clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.polardbx.aliyun.com/v1/mutate-polardbx-aliyun-com-v1-polardbxclusterknobs
  name: "polardbxclusterknobs-mutate.polardbx.aliyun.com"
  sideEffects: None
  rules:
  - apiGroups:
    - polardbx.aliyun.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - polardbxclusterknobs
    scope: "Namespaced"