apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.controllerManager.name}}-config
  namespace: {{ .Release.Namespace }}
data:
  webhook.yaml: |-
    validator:

    default:
      protocol_version: {{ .Values.webhook.defaults.protocolVersion }}
      storage_engine: {{ .Values.webhook.defaults.storageEngine }}
      service_type: {{ .Values.webhook.defaults.serviceType }}
      upgrade_strategy: {{ .Values.webhook.defaults.upgradeStrategy }}
  config.yaml: |-
    images:
      repo: {{ .Values.imageRepo }}
      common:
        {{- if .Values.useLatestImage }}
        prober: {{ .Values.images.probeProxy }}:latest
        exporter: {{ .Values.images.polardbxExporter }}:latest
        {{- else }}
        prober: {{ .Values.images.probeProxy }}:{{ .Values.imageTag | default .Chart.AppVersion }}
        exporter: {{ .Values.images.polardbxExporter }}:{{ .Values.imageTag | default .Chart.AppVersion }}
        {{- end }}
      compute:
        {{- if .Values.useLatestImage }}
        init: {{ .Values.images.polardbxInit}}:latest
        {{- else }}
        init: {{ .Values.images.polardbxInit}}:{{ .Values.imageTag | default .Chart.AppVersion }}
        {{- end }}
        engine: {{ .Values.clusterDefaults.images.galaxysql }}:{{ .Values.clusterDefaults.version }}
      cdc:
        engine: {{ .Values.clusterDefaults.images.galaxycdc}}:{{ .Values.clusterDefaults.version }}
      store:
        galaxy:
          engine: {{ .Values.clusterDefaults.images.galaxyengine }}:{{ .Values.clusterDefaults.version }}
          exporter: prom/mysqld-exporter:master
        xcluster:
          exporter: prom/mysqld-exporter:master
{{- if .Values.extension.config.images.store }}
{{ toYaml .Values.extension.config.images.store | indent 8 }}
{{- end}}
    scheduler:
      enable_master: {{ .Values.controllerManager.config.scheduler.allowScheduleOnMaster }}
    cluster:
      enable_exporters: {{ .Values.controllerManager.config.enableExporters }}
      enable_aliyun_ack_resource_controller: {{ .Values.controllerManager.config.scheduler.enableAliyunAckResourceController }}
      enable_debug_mode_for_compute_nodes: false
      enable_privileged_container: {{ .Values.controllerManager.config.container.privileged }}
    store:
      enable_privileged_container: {{ .Values.controllerManager.config.container.privileged }}
      host_paths:
        tools: {{ .Values.node.volumes.data }}/cache/tools/xstore
        volume_data: {{ .Values.node.volumes.data }}/xstore
        volume_log: {{ .Values.node.volumes.log }}/xstore
        volume_filestream: {{ .Values.node.volumes.filestream }}
      hpfs_endpoint: {{.Values.hostPathFileService.name}}:{{ .Values.hostPathFileService.port }}
{{- if .Values.extension.config.security }}
    security:
{{ toYaml .Values.extension.config.security | indent 6 }}
{{- end}}
    oss:
      oss_endpoint: {{ .Values.hostPathFileService.ossEndpoint }}
      oss_bucket: {{ .Values.hostPathFileService.ossBucket }}
      oss_access_key: {{ .Values.hostPathFileService.ossAccessKey }}
      oss_access_secret: {{ .Values.hostPathFileService.ossAccessSecret }}
{{- if .Values.node.nfs }}
    nfs:
      nfs_path: {{ .Values.node.nfs.path }}
      nfs_server: {{ .Values.node.nfs.server }}
{{- end}}