apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hostPathFileService.name}}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    sinks:
{{ toYaml .Values.hostPathFileService.sinks | indent 7 }}
    backupBinlogConfig:
      rootDirectories:
        - {{ .Values.node.volumes.data }}/xstore
        - {{ .Values.node.volumes.log }}/xstore
    cGroupControlConfig:
      cpu_set_strategy: {{ .Values.hostPathFileService.cpuBind.strategy }}
      

