apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hostPathFileService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: polardbx-hpfs
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: polardbx-hpfs
  ports:
  - name: hpfs
    port: {{ .Values.hostPathFileService.port }}
    targetPort: hpfs
  - name: filestream
    port: {{ .Values.hostPathFileService.fsPort }}
    targetPort: filestream